# Site settings
title: Jack Ellis
email: jackellis1504@gmail.com
description: >-
  I am a web developer with a Master's in Computer Science and a freelance theatre backstage
  person with experience in sound design, set design and construction, and changeovers.
twitter_username: gingertronmk1
github_username:  gingertronmk1

future: true

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: nested
