version: "3"

services:
  node:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/local/node.dockerfile
    volumes:
      - "./:/srv"
    command: tail -f /dev/null
    ports:
      - "80:80"
      - "23456:23456"

networks:
  app-network:
    driver: bridge
