name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch origin
        shell: bash
        run: git fetch origin
      - name: NPM install and run production
        shell: bash
        run: |
          npm install
          npm run production
      - name: Add and commit new files
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Production assets"
      - name: Checkout to `live` and push
        shell: bash
        run: |
          git checkout live
          git merge -X theirs master --allow-unrelated-histories
          git push origin live


