name: get_superleague_stats

on:
  schedule:
    - cron: "0 0 * * 3"
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  download_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create folder
        run: mkdir -p assets/json/threads
      - name: Work with file?
        run: ./src/assets/download_stats.sh
      - name: Now do git things
        run: |
          DATE="stats_download_$(date +%Y-%m-%d-%H-%M-%S)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b $DATE
          git add src/assets/json
          git commit -m "Updated threads at $DATE"
          git push -u origin $DATE
