name: get_superleague_stats

on:
  schedule:
    - cron: "0 0 * * 3"
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  download_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Create folder
        run: mkdir -p assets/json/threads
      - name: Work with file?
        run: |
          THREADSJSON=`cat assets/json/threads.json`
          echo $THREADSJSON
          CURRENT=`echo $THREADSJSON | jq 'to_entries[-1].value'`
          THREADS=`echo $CURRENT | jq '.[]' -r`
          echo $THREADS
          for THREAD in $THREADS
          do
            THREADURL="https://api.reddit.com/r/superleague/comments/$THREAD"
            OUTPUTPATH="assets/json/threads/$THREAD.json"
            echo $THREADURL
            echo $OUTPUTPATH
            curl -A "random" $THREADURL -o $OUTPUTPATH
            cat $OUTPUTPATH
            sleep 60
          done
          ls -la assets/json
      - name: Now do git things
        run: |
          DATE="stats_download_$(date +%Y-%m-%d-%H-%M-%S)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b $DATE
          git add assets/json
          git commit -m "Updated threads at $DATE"
          git push -u origin $DATE
