name: Auto-Label

on: pull_request

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Request Labeller
        uses: GingertronMk1/pull-request-labeler@v3
        with:
          configuration-path: ".github/labelconfig.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
