name: Lint

on:
  pull_request: 
    branches: master

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        shell: bash
        run: npm run lint
